### ISSUE TITLE
Icons missing and no text rendered

### ISSUE THREAD

**Issue by ottz0** [devbridge/Styleguide#127]
Hi have gulp start-styleguide running and a gulp server running on a different port and am browsing http://localhost:8000/styleguide/index.html but the icons are broken and can't see any rendered "The quick brown fox", the containers are empty
![ss](https://cloud.githubusercontent.com/assets/7971800/14814332/23f6851a-0be9-11e6-90fb-05a7f5433060.png)

**Comment by krja1012** [comment]
Hi,
Same problem here.
And "New Snippet" Button and menu Button are also missing.

Node v.5.11. x64 installed and using live-server.

**Comment by VaclovasV** [comment]
maybe you are running live-server on same port? try to use live-server --port=8181, this should help

**Comment by krja1012** [comment]
Thanks a lot, that helped! Now it's running fine.

**Comment by ottz0** [comment]
gulp start-styleguide is running on port 8000 and live server is running on port 8181, still the same

**Comment by gediminas-s** [comment]
@ottz0 , in order to see 'The quick brown fox..' or color palette, you need to scrape your scss variables. Check documentation for that. 
Regarding missing icons in the header, they are web icons loaded from cdn. Please check if your localhost supports .woff format, or allowing external resources.

**Comment by markplewis** [comment]
For me, the fonts are being loaded from my local `styleguide/content/fonts` directory instead of a CDN, and I was getting the following errors in my console:

    Failed to decode downloaded font: http://127.0.0.1:51008/styleguide/content/fonts/fontawesome-webfont.woff2
    OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
    Failed to decode downloaded font: http://127.0.0.1:51008/styleguide/content/fonts/fontawesome-webfont.woff
    OTS parsing error: incorrect file size in WOFF header
    Failed to decode downloaded font: http://127.0.0.1:51008/styleguide/content/fonts/fontawesome-webfont.ttf
    OTS parsing error: incorrect entrySelector for table directory

According to the following StackOverflow answer, the font files may have been corrupted. Downloading the fonts directly from fontawesome.com and replacing them in my local `styleguide/content/fonts` directory fixed the problem for me.

http://stackoverflow.com/questions/32475982/fontawesome-fails-to-load-fonts-locally-and-in-electron-app#answer-33792610

> In my situation, Git was treating the file as a text file, and messing with its "line endings". This was corrupting the file.
> 
> Adjusting the .gitconfig to recognize *.woff files as binary, then removing the file, and adding a new copy from https://github.com/FortAwesome/Font-Awesome/raw/v4.2.0/fonts/fontawesome-webfont.woff solved the issue for me.

**Comment by gediminas-s** [comment]
Thanks for update, we going to make changes on our end as well.

**Comment by mplunkett5** [comment]
Downloading from fontawesome and overwriting the fonts installed worked for me as well :)

**Comment by yumyo** [comment]
The problem is still occurring in **Firefox (45.0.1)** on **Mac OS X (10.11.5)** 
Styleguide published on a remote server. No similar errors in **Safari**, **Chrome** or **Opera**

Here follows my console output:

`downloadable font: WOFF2: Failed to read 'length' or it does not match the actual file size (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.woff2 main.css:1:25503`

`downloadable font: Failed to convert WOFF 2.0 font to SFNT (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.woff2 main.css:1:25503`

`downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.woff2`

`downloadable font: incorrect file size in WOFF header (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.woff main.css:1:25503`

`downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.woff main.css:1:25503`

`downloadable font: bad search range (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:3) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.ttf main.css:1:25503`

`downloadable font: incorrect entrySelector for table directory (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:3) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.ttf main.css:1:25503`

`downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:3) source: http://my-domain/styleguide/content/fonts/fontawesome-webfont.ttf`
